---
- hosts: all
  become: yes

  tasks:
  - name: install cowsay
    apt:
      name: cowsay
      state: present


  - name: install figlet
    apt:
      name: figlet
      state: present

  - name: install neofetch
    apt:
      name: neofetch
      state: present